resources:
- name: git
  type: git
  source:
    branch: master
    uri: ssh://git@concourse-git/git-server/repos/myrepo.git
    private_key: ((github-private-key))

jobs:
- name: build-and-test
  plan:
    - aggregate:
      - get: git
        trigger: true
    - task: build-and-test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine}
        run:
          path: echo
          args: ["Hello, build!"]
- name: deploy-test
  serial: true
  plan:
    - aggregate:
      - get: git
        passed: [build-and-test]
        trigger: true
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine}
        run:
          path: echo
          args: ["Hello, deploy to test!"]

- name: deploy-prod
  serial: true
  plan:
    - aggregate:
      - get: git
        passed: [deploy-test]
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine}
        run:
          path: echo
          args: ["Hello, deploy to prod!"]